from __future__ import annotations

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import yaml
from PIL import Image
from torchvision import datasets


@dataclass(frozen=True)
class SocialSplit:
    """固定的社会化学习任务划分。"""

    dataset: str
    data_dir: Path
    num_agents: int
    num_classes: int
    class_split: dict[int, list[int]]
    model_split: dict[int, str]
    seed: int


def load_social_split(config_path: str | Path) -> SocialSplit:
    """从项目 yaml 配置读取固定 agent/class/model split。"""
    config_path = Path(config_path)
    with config_path.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    dataset_cfg = cfg.get("dataset", {})
    agents_cfg = cfg.get("agents", {})
    runtime_cfg = cfg.get("runtime", {})

    dataset_name = str(dataset_cfg.get("name", "cifar100"))
    if dataset_name != "cifar100":
        raise ValueError(f"当前 baseline adapter 只支持 cifar100，收到: {dataset_name}")

    class_split = _normalize_agent_dict(agents_cfg.get("class_split", {}), value_type=int)
    model_split = _normalize_agent_dict(agents_cfg.get("model_split", {}), value_type=str)
    return SocialSplit(
        dataset=dataset_name,
        data_dir=Path(dataset_cfg.get("data_dir", "./data")),
        num_agents=int(agents_cfg.get("num_agents", len(class_split))),
        num_classes=int(agents_cfg.get("num_classes", 100)),
        class_split=class_split,
        model_split=model_split,
        seed=int(runtime_cfg.get("seed", 0)),
    )


def load_cifar100_arrays(data_dir: str | Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """读取 CIFAR-100 原始 uint8 图像和全局标签。"""
    train_set = datasets.CIFAR100(root=str(data_dir), train=True, download=False)
    test_set = datasets.CIFAR100(root=str(data_dir), train=False, download=False)
    return (
        np.asarray(train_set.data, dtype=np.uint8),
        np.asarray(train_set.targets, dtype=np.int64),
        np.asarray(test_set.data, dtype=np.uint8),
        np.asarray(test_set.targets, dtype=np.int64),
    )


def select_indices_by_classes(
    labels: np.ndarray,
    classes: Iterable[int],
    per_class: int | None = None,
    seed: int = 0,
) -> np.ndarray:
    """按全局类别选择样本索引，可限制每类样本数。"""
    rng = np.random.default_rng(seed)
    selected: list[np.ndarray] = []
    for cls in classes:
        cls_indices = np.flatnonzero(labels == int(cls))
        if per_class is not None:
            if per_class > len(cls_indices):
                raise ValueError(f"class {cls} 只有 {len(cls_indices)} 张，无法选择 {per_class} 张")
            cls_indices = rng.choice(cls_indices, size=per_class, replace=False)
        selected.append(np.sort(cls_indices))
    if not selected:
        return np.array([], dtype=np.int64)
    return np.concatenate(selected).astype(np.int64)


def labels_stat(labels: np.ndarray, classes: Iterable[int]) -> dict[str, int]:
    """统计每个类别的样本数，manifest 使用字符串 key 保持 json 兼容。"""
    return {str(int(cls)): int(np.sum(labels == int(cls))) for cls in classes}


def export_fedre_npz(split: SocialSplit, output_dir: str | Path) -> Path:
    """导出 FedRE/PFLlib 风格的 per-client npz 数据。"""
    output_dir = Path(output_dir)
    train_dir = output_dir / "Cifar100" / "train"
    test_dir = output_dir / "Cifar100" / "test"
    train_dir.mkdir(parents=True, exist_ok=True)
    test_dir.mkdir(parents=True, exist_ok=True)

    train_x, train_y, test_x, test_y = load_cifar100_arrays(split.data_dir)
    statistic = {}
    for agent_id, classes in split.class_split.items():
        train_idx = select_indices_by_classes(train_y, classes)
        test_idx = select_indices_by_classes(test_y, classes)
        train_dict = {"x": _to_chw_float(train_x[train_idx]), "y": train_y[train_idx]}
        test_dict = {"x": _to_chw_float(test_x[test_idx]), "y": test_y[test_idx]}
        np.savez_compressed(train_dir / f"{agent_id}.npz", data=train_dict)
        np.savez_compressed(test_dir / f"{agent_id}.npz", data=test_dict)
        statistic[str(agent_id)] = {
            "classes": [int(c) for c in classes],
            "train": labels_stat(train_y[train_idx], classes),
            "test": labels_stat(test_y[test_idx], classes),
        }

    _write_json(
        output_dir / "Cifar100" / "config.json",
        {
            "num_clients": split.num_agents,
            "num_classes": split.num_classes,
            "non_iid": True,
            "balance": True,
            "partition": "class-disjoint-25",
            "Size of samples for labels in clients": statistic,
            "note": "Generated by DatasetDistillationforSocialLearning baseline_adapters.",
        },
    )
    return output_dir / "Cifar100"


def export_masc_imagefolder(split: SocialSplit, output_dir: str | Path, ipc: int) -> Path:
    """导出 MASC ImageFolder 数据目录，训练集按 IPC 限制。"""
    output_dir = Path(output_dir)
    train_x, train_y, test_x, test_y = load_cifar100_arrays(split.data_dir)
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    manifest = {
        "format": "masc_imagefolder",
        "ipc": int(ipc),
        "classes_per_agent": {str(k): v for k, v in split.class_split.items()},
        "tasks": {},
    }
    for agent_id, classes in split.class_split.items():
        train_idx = select_indices_by_classes(train_y, classes, per_class=ipc, seed=split.seed + agent_id)
        test_idx = select_indices_by_classes(test_y, classes)
        task_dir = output_dir / f"Task_{agent_id}"
        _write_imagefolder(train_x, train_y, train_idx, task_dir / f"traindata_{agent_id}")
        _write_imagefolder(test_x, test_y, test_idx, task_dir / f"testdata_{agent_id}")
        manifest["tasks"][str(agent_id)] = {
            "train_images": int(len(train_idx)),
            "test_images": int(len(test_idx)),
            "train_per_class": labels_stat(train_y[train_idx], classes),
            "test_per_class": labels_stat(test_y[test_idx], classes),
        }

    _write_json(output_dir / "manifest.json", manifest)
    return output_dir


def export_split_metadata(split: SocialSplit, output_dir: str | Path, ipc: int | None = None) -> Path:
    """导出 FedProto/DeSA 可复用的固定 split 元数据。"""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    train_x, train_y, test_x, test_y = load_cifar100_arrays(split.data_dir)

    metadata = {
        "dataset": split.dataset,
        "num_agents": split.num_agents,
        "num_classes": split.num_classes,
        "ipc": ipc,
        "seed": split.seed,
        "class_split": {str(k): v for k, v in split.class_split.items()},
        "model_split": {str(k): v for k, v in split.model_split.items()},
        "agents": {},
    }
    for agent_id, classes in split.class_split.items():
        train_idx = select_indices_by_classes(train_y, classes)
        test_idx = select_indices_by_classes(test_y, classes)
        packet_idx = select_indices_by_classes(train_y, classes, per_class=ipc, seed=split.seed + agent_id) if ipc else []
        metadata["agents"][str(agent_id)] = {
            "classes": [int(c) for c in classes],
            "train_indices": [int(i) for i in train_idx],
            "test_indices": [int(i) for i in test_idx],
            "packet_indices_ipc": [int(i) for i in packet_idx],
            "train_count": int(len(train_idx)),
            "test_count": int(len(test_idx)),
        }

    metadata["dataset_sizes"] = {
        "train": int(len(train_x)),
        "test": int(len(test_x)),
    }
    _write_json(output_dir / "split_metadata.json", metadata)
    return output_dir / "split_metadata.json"


def build_export_manifest(split: SocialSplit, output_dir: str | Path, paths: dict[str, str]) -> Path:
    """写出本次 baseline 导出的总 manifest。"""
    output_dir = Path(output_dir)
    manifest_path = output_dir / "manifest.json"
    _write_json(
        manifest_path,
        {
            "dataset": split.dataset,
            "num_agents": split.num_agents,
            "num_classes": split.num_classes,
            "seed": split.seed,
            "class_split": {str(k): v for k, v in split.class_split.items()},
            "model_split": {str(k): v for k, v in split.model_split.items()},
            "exports": paths,
        },
    )
    return manifest_path


def _normalize_agent_dict(raw: dict, value_type):
    """统一 agent_0 / 0 两种 key 格式。"""
    normalized = {}
    for key, value in raw.items():
        agent_id = int(str(key).replace("agent_", ""))
        if isinstance(value, list):
            normalized[agent_id] = [value_type(v) for v in value]
        else:
            normalized[agent_id] = value_type(value)
    return normalized


def _to_chw_float(images_hwc: np.ndarray) -> np.ndarray:
    """FedRE 读取后不再做 transform，这里转成 [0,1] CHW float。"""
    return np.transpose(images_hwc.astype(np.float32) / 255.0, (0, 3, 1, 2))


def _write_imagefolder(images: np.ndarray, labels: np.ndarray, indices: np.ndarray, root: Path) -> None:
    """写出 ImageFolder 目录，目录名保留全局类别 id。"""
    for index in indices:
        label = int(labels[index])
        class_dir = root / f"{label:03d}"
        class_dir.mkdir(parents=True, exist_ok=True)
        Image.fromarray(images[index]).save(class_dir / f"{int(index):05d}.png")


def _write_json(path: Path, payload: dict) -> None:
    """写 JSON 文件并保持稳定排序。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False, sort_keys=True)
